messages:
  # Specify the format for the voucher item
  voucher-item-name-format: '&6{item} Voucher'
  voucher-item-name-format-locked: '&8{item} Voucher'
  voucher-item-material: PAPER
  voucher-item-lore-format:
    - '&e<Tier {tier}>'
    - '&7Grants the ability to craft'
    - '&7and use &8{item}'
  voucher-farm-lore-format:
    - '&e<Tier {tier}>'
    - '&7Grants the ability to plant'
    - '&8{seed}&7 to grow &8{block}'
    - '&7Grants the ability to craft'
    - '&7and use &8{food}'
  unlocked-message: '&a<Unlocked>'
  locked-message: '&7<Locked>'
  # The message shown when a player attempts an action with the invalid voucher. Set to '' if you do not
  # want a message.
  deny-message: '&cYou must unlock the voucher for that item to use it!'
miscellaneous:
  # For material vouchers, if a block is specified, should the plugin block placement of said block?
  prevent-block-placement: true
  # For material vouchers, if a block is specified, should the plugin block mining of said block?
  prevent-block-mining: true
  # For farm vouchers, should the crafting of the food material be denied
  block-food-material-craft: false
  # For farm vouchers, should the consumption of the food material be denied
  block-food-material-consume: false
  gui-border-material1: BLACK_STAINED_GLASS_PANE
  gui-border-material2: GRAY_STAINED_GLASS_PANE

